[project]
name = "insurance"
version = "0.1.0"
description = "Health-insurance model"
authors = [{name = "Hubert Murawski"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
